In [4]:
import torch
print(torch.__version__)

2.4.0


Pytorch tensors are created using torch.tensor()

In [6]:
scalar = torch.tensor(7)
scalar

tensor(7)

You can use "ndim" to get the number of dimensions of a tensor

In [7]:
scalar.ndim

0

Get tensor back to python int use item() function

In [8]:
scalar.item()

7

Tensor with more than one dimension is called vector

In [10]:
vector = torch.tensor([2,3]) 
vector

tensor([2, 3])

In [11]:
vector.ndim

1

we can use "shape" to get the number of elements of a tensor

In [12]:
vector.shape

torch.Size([2])

Create a two dimensional matrix

In [14]:
MATRIX = torch.tensor([[1,2],
                       [3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

The shape of the matrix is 2 rows and 2 columns

In [15]:
MATRIX.shape

torch.Size([2, 2])

In [16]:
MATRIX.ndim

2

Create a tensor

In [17]:
TENSOR = torch.tensor([[[1,2,3,],
                        [2,3,4],
                        [4,5,6]]])
TENSOR

tensor([[[1, 2, 3],
         [2, 3, 4],
         [4, 5, 6]]])

In [18]:
TENSOR.shape

torch.Size([1, 3, 3])

In [19]:
TENSOR.ndim

3

### Random Tensors
Why random tensors?

Random tensors are important because the way maany neural networks learn is that they start with tensors with full of random numbers and then adjust those random numbers to better represent the data